[package]
name = "stitcher"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.0"
quinn = "0.11.9"
rcgen = "0.14.5"
rustls = { version = "0.23.35", features = ["ring"] }
tokio = { version = "1.48.0", features = ["full"] }
